### PR TITLE
Added background service and local push notification.

### PR DESCRIPTION
**Pull request by mikeng13**
@enginnerd @styliii

### CODE REVIEW

**Comment by mikeng13** [comment]
Yeah I would think that we want greater than or equal or less than or equal its pretty hard to get an exact equals. Right now its only > or < so I'll change to add the equal operator to those.

**Comment by styliii** [comment]
how do i test the push notification part?

I created some alerts, and they're triggering...but nothing shows up on the phone?

**Comment by mikeng13** [comment]
Ok I think I found the problem. I am pushing a commit for a fix.

**Comment by mikeng13** [comment]
Closing this to avoid any more merge conflicts. We should open new issues for bugs or other related work.

**Pull request merged**
