### PR TITLE
Initial styling on home page and also fixed some bugs.

### PR DESCRIPTION
**Pull request by mikeng13**
@enginnerd @styliii 

Fixes issue [Issue 89](https://github.com/FinNerds/AndroidApp/issues/89), [Issue 74](https://github.com/FinNerds/AndroidApp/issues/74), and [Issue 59](https://github.com/FinNerds/AndroidApp/issues/59)

### CODE REVIEW

**Comment by mikeng13** [comment]
@enginnerd @styliii 

I redid the home page a little bit. I removed the pie chart and replaced it with a bar chart that pretty much shows the top gainers/losers in your portfolio. Let me know what you guys think! Here's a screenshot:

screenshot_2015-04-03-22-10-36

**Comment by enginnerd** [comment]
nice! that looks really good.  Does the bar chart scroll if I have more stocks?

**Comment by enginnerd** [comment]
good to merge, i'll merge.

**Comment by styliii** [comment]
looks beautiful!

**Comment by mikeng13** [comment]
Thanks! @enginnerd yeah the bar chart scrolls if there are more. I'll think of a way to make that more obvious.

**Pull request merged**
